### ISSUE TITLE
Do market orders planned ? Can you share benchmark script .

### ISSUE THREAD

**Issue by KabDeveloper** [alexey-ernest/go-hft-orderbook#1]
Hi,

Do market orders planned ?

Can you share your benchmark script please ?

Thank you

**Comment by bcashier** [comment]
Also, do you have a usage example ?

**Comment by alexey-ernest** [comment]
The benchmarks are in the test files, e.g. https://github.com/alexey-ernest/go-hft-orderbook/blob/master/orderbook_test.go

**Comment by alexey-ernest** [comment]
> Hi,
> 
> Do market orders planned ?
> 
> Can you share your benchmark script please ?
> 
> Thank you

No market orders planned, as it is not intended for a matching engine, rather than for managing your own copy of an orderbook in memory to make trading decisions.
