### ISSUE TITLE
Bug in DeleteAskLimit functionality in Orderbook

### ISSUE THREAD

**Issue by ankit257** [alexey-ernest/go-hft-orderbook#3]
In orderbook.go file in line #123, it should be 
`limit := this.askLimitsCache[price]`
instead of 
`limit := this.bidLimitsCache[price]`

**Comment by ankit257** [comment]
opened a PR 
https://github.com/alexey-ernest/go-hft-orderbook/pull/4

**Comment by alexey-ernest** [comment]
Thank you.
